// USBRemote/Client/src/App.jsx
import React, { useState, useEffect, useRef } from 'react';
import { 
  Shield, Usb, Laptop, Radio, Send, X, 
  Lock, RefreshCw, Trash2, FolderSync, 
  MessageSquare, Settings, AlertCircle, Terminal, 
  Key, ShieldCheck, Activity, LogOut, Cloud, Link2
} from 'lucide-react';

export default function App() {
  // System states
  const [computerName, setComputerName] = useState('Local-PC');
  const [drives, setDrives] = useState([]);
  const [activeUSB, setActiveUSB] = useState(null); // The USB key currently read
  const [mode, setMode] = useState('select'); // 'select', 'sender', 'receiver', 'session'
  
  // Connection Configuration
  const [serverUrl, setServerUrl] = useState('ws://localhost:9000'); // Can be local ws or Vercel https://...
  const [serverStatus, setServerStatus] = useState('disconnected');
  const [socket, setSocket] = useState(null);
  const [receiverCode, setReceiverCode] = useState(''); // Code shown on receiver or entered on sender
  const [pairingState, setPairingState] = useState('idle'); // 'idle', 'requesting', 'incoming-request', 'authenticating', 'success', 'failed'
  const [pairingMessage, setPairingMessage] = useState('');
  const [incomingRequest, setIncomingRequest] = useState(null); // { peerCert, peerComputerName, challenge }
  
  // IDs generated by server for tracking
  const [clientId, setClientId] = useState(''); // senderId or receiverId
  
  // Active Session states
  const [peerCert, setPeerCert] = useState(null);
  const [peerComputerName, setPeerComputerName] = useState('');
  const [chatMessages, setChatMessages] = useState([]);
  const [chatInput, setChatInput] = useState('');
  const [ping, setPing] = useState(12); // ms
  const [sessionActive, setSessionActive] = useState(false);
  const [clipboardSynced, setClipboardSynced] = useState(false);

  // Security and DB states
  const [trustedDevices, setTrustedDevices] = useState([]);
  const [securityLogs, setSecurityLogs] = useState([]);
  const [registerLabel, setRegisterLabel] = useState('Personal Key');

  // Input states
  const [connectCodeInput, setConnectCodeInput] = useState('');
  const [showConfig, setShowConfig] = useState(false);

  // Simulated USB paths
  const [simFolderA, setSimFolderA] = useState('./usb_key_a');
  const [simFolderB, setSimFolderB] = useState('./usb_key_b');

  // References
  const socketRef = useRef(null);
  const logEndRef = useRef(null);
  const pollIntervalRef = useRef(null);

  // Load initial settings and check USB drives
  useEffect(() => {
    // Get host name
    window.electronAPI.getComputerName().then(name => setComputerName(name));
    
    // Load trusted devices
    loadTrustedDevices();

    // Load security logs
    loadSecurityLogs();

    // Fetch initially connected USB drives
    refreshDrives();

    // Subscribe to USB connection changes
    const unsubscribe = window.electronAPI.onUSBChange((data) => {
      refreshDrives();
      addSecurityLog('USB', `USB Event: Device ${data.event}ed - ${data.drive.label} (${data.drive.driveLetter})`);
    });

    return () => {
      unsubscribe();
      cleanupConnections();
    };
  }, []);

  // Auto-scroll logs
  useEffect(() => {
    logEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [securityLogs]);

  const loadTrustedDevices = async () => {
    const devices = await window.electronAPI.getTrustedDevices();
    setTrustedDevices(devices);
  };

  const loadSecurityLogs = async () => {
    const logs = await window.electronAPI.getLogs();
    setSecurityLogs(logs);
  };

  const addSecurityLog = (category, message, details = {}) => {
    setSecurityLogs(prev => [
      ...prev,
      {
        timestamp: new Date().toISOString(),
        level: 'INFO',
        category,
        message,
        details
      }
    ]);
  };

  const refreshDrives = async () => {
    const connected = await window.electronAPI.getConnectedDrives();
    setDrives(connected);

    // If there is an active selected USB, check if it's still plugged in
    if (activeUSB) {
      const stillConnected = connected.some(d => d.driveLetter === activeUSB.driveLetter);
      if (!stillConnected) {
        setActiveUSB(null);
        setMode('select');
        addSecurityLog('USB', 'Active USB security key was unplugged. Session terminated.');
        cleanupConnections();
      }
    } else {
      // Auto-read first connected drive if it contains a key
      for (const d of connected) {
        const res = await window.electronAPI.readUSBKey(d.driveLetter);
        if (res.success) {
          setActiveUSB({
            driveLetter: d.driveLetter,
            label: d.label,
            cert: res.certificate,
            privateKey: res.privateKey
          });
          addSecurityLog('USB', `Authenticated security key loaded from drive ${d.driveLetter}`);
          break;
        }
      }
    }
  };

  // Connect/Create Simulated USB Key
  const handleSimulateUSB = async (pathStr, label) => {
    const res = await window.electronAPI.addSimulatedUSB(pathStr, label);
    if (res.success) {
      addSecurityLog('USB', `Registered simulated USB path: ${pathStr}`);
      refreshDrives();
    } else {
      alert(`Simulation failed: ${res.error}`);
    }
  };

  // Remove Simulated USB Key
  const handleRemoveSimulatedUSB = async (pathStr) => {
    await window.electronAPI.removeSimulatedUSB(pathStr);
    addSecurityLog('USB', `Removed simulated USB path: ${pathStr}`);
    refreshDrives();
  };

  // Format/Register a connected drive as a USB security key
  const handleFormatDrive = async (driveLetter) => {
    if (!registerLabel.trim()) return;
    const res = await window.electronAPI.registerUSBDrive(driveLetter, registerLabel);
    if (res.success) {
      addSecurityLog('USB', `Registered security certificate on drive ${driveLetter}`);
      refreshDrives();
    } else {
      alert(`Registration failed: ${res.error}`);
    }
  };

  // Clean WebSocket and Polling intervals
  const cleanupConnections = () => {
    if (socketRef.current) {
      socketRef.current.close();
      socketRef.current = null;
    }
    if (pollIntervalRef.current) {
      clearInterval(pollIntervalRef.current);
      pollIntervalRef.current = null;
    }
    setSocket(null);
    setServerStatus('disconnected');
    setPairingState('idle');
    setSessionActive(false);
  };

  const isHttpServer = () => {
    return serverUrl.startsWith('http://') || serverUrl.startsWith('https://');
  };

  // Establish connection and register on server
  const initializeConnection = async (selectedRole) => {
    if (!activeUSB) {
      alert('No USB Security Key authenticated.');
      return;
    }

    cleanupConnections();
    setServerStatus('connecting');
    setPairingState('idle');
    setPairingMessage('Connecting to signaling cloud...');

    if (isHttpServer()) {
      // Use Vercel Serverless HTTP Polling
      addSecurityLog('NET', `Initializing connection to Vercel Endpoint: ${serverUrl}`);
      try {
        if (selectedRole === 'receiver') {
          const res = await fetch(`${serverUrl}/api/register-receiver`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ cert: activeUSB.cert, computerName })
          });
          const data = await res.json();
          if (data.success) {
            setReceiverCode(data.code);
            setClientId(data.receiverId);
            setServerStatus('connected');
            setMode('receiver');
            setPairingMessage('Waiting for incoming secure connections...');
            addSecurityLog('NET', `Registered on Vercel. Code: ${data.code}`);
            
            // Start polling Vercel api
            startVercelPolling(data.receiverId, 'receiver');
          } else {
            throw new Error(data.error);
          }
        } else {
          const res = await fetch(`${serverUrl}/api/register-sender`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ cert: activeUSB.cert, computerName })
          });
          const data = await res.json();
          if (data.success) {
            setClientId(data.senderId);
            setServerStatus('connected');
            setMode('sender');
            setPairingMessage('Ready to secure connect.');
            addSecurityLog('NET', `Registered as Sender on Vercel. ID: ${data.senderId}`);
          } else {
            throw new Error(data.error);
          }
        }
      } catch (err) {
        setServerStatus('disconnected');
        setPairingState('failed');
        setPairingMessage(`Vercel Connect Error: ${err.message}`);
        addSecurityLog('NET', `Failed to register on Vercel: ${err.message}`);
      }
    } else {
      // Use standard WebSocket connection (local dev server)
      addSecurityLog('NET', `Connecting to WebSocket relay: ${serverUrl}`);
      const ws = new WebSocket(serverUrl);
      socketRef.current = ws;
      setSocket(ws);

      ws.onopen = () => {
        setServerStatus('connected');
        addSecurityLog('NET', 'Signaling server connected.');
        
        if (selectedRole === 'receiver') {
          ws.send(JSON.stringify({
            type: 'register-receiver',
            cert: activeUSB.cert,
            computerName: computerName
          }));
          setPairingMessage('Registering security keys on cloud...');
        } else {
          ws.send(JSON.stringify({
            type: 'register-sender',
            cert: activeUSB.cert,
            computerName: computerName
          }));
          setMode('sender');
          setPairingState('idle');
        }
      };

      ws.onmessage = async (event) => {
        let msg;
        try {
          msg = JSON.parse(event.data);
        } catch (e) {
          return;
        }
        handleIncomingMessage(msg);
      };

      ws.onclose = () => {
        setServerStatus('disconnected');
        addSecurityLog('NET', 'Signaling server connection lost.');
      };
    }
  };

  // HTTP polling loop for Vercel
  const startVercelPolling = (id, role) => {
    if (pollIntervalRef.current) clearInterval(pollIntervalRef.current);
    
    pollIntervalRef.current = setInterval(async () => {
      try {
        const res = await fetch(`${serverUrl}/api/poll`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ id, role })
        });
        const msg = await res.json();
        
        if (msg && msg.type !== 'idle' && msg.type !== 'waiting') {
          handleIncomingMessage(msg);
        }
      } catch (err) {
        console.error('Polling error:', err);
      }
    }, 1500);
  };

  // Core Message Router (handles WebSocket and HTTP Polling messages identically)
  const handleIncomingMessage = async (msg) => {
    switch (msg.type) {
      case 'registered':
        setReceiverCode(msg.code);
        setMode('receiver');
        setPairingState('idle');
        setPairingMessage('Waiting for incoming secure connections...');
        addSecurityLog('NET', `Receiver registered. Security Code: ${msg.code}`);
        break;

      case 'sender-registered':
        setPairingMessage('Ready to secure connect.');
        break;

      case 'incoming-request': {
        const { challenge, peerCert, peerComputerName } = msg;
        setIncomingRequest({ challenge, peerCert, peerComputerName });
        setPairingState('incoming-request');
        addSecurityLog('SECURITY', `Incoming connection request from ${peerComputerName}`);
        break;
      }

      case 'auth-challenge': {
        const { challenge, peerCert, peerComputerName } = msg;
        setPairingState('authenticating');
        setPairingMessage('Performing mutual authentication...');
        addSecurityLog('SECURITY', `Signaling challenge received. Computing signature...`);

        // Sign challenge using physical/simulated private key
        const signature = await window.electronAPI.signChallenge(challenge, activeUSB.privateKey);
        
        if (isHttpServer()) {
          // Submit signature to Vercel
          await fetch(`${serverUrl}/api/submit-signature`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ id: clientId, role: 'sender', signature })
          });
          // Start polling for receiver verification
          startVercelPolling(clientId, 'sender');
        } else {
          socketRef.current.send(JSON.stringify({
            type: 'auth-signature',
            signature: signature
          }));
        }
        break;
      }

      case 'verify-peer-signature': {
        const { signature, challenge, peerCert } = msg;
        addSecurityLog('SECURITY', `Verifying signature of peer ${peerCert.owner}...`);

        // Verify signature locally using peer's public key from cert
        const verified = await window.electronAPI.verifyChallenge(challenge, signature, peerCert.publicKey);
        addSecurityLog('SECURITY', `Mutual verification status: ${verified ? 'SUCCESS' : 'FAILED'}`);
        
        if (isHttpServer()) {
          await fetch(`${serverUrl}/api/submit-verification`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ id: clientId, role: mode, verified })
          });
        } else {
          socketRef.current.send(JSON.stringify({
            type: 'verify-peer-result',
            verified: verified
          }));
        }

        if (verified) {
          setPeerCert(peerCert);
          setPeerComputerName(peerCert.owner);
        } else {
          setPairingState('failed');
          setPairingMessage('Mutual authentication signature check failed.');
        }
        break;
      }

      case 'auth-success':
      case 'active-session': {
        if (!sessionActive) {
          addSecurityLog('SECURITY', 'Mutual USB Authentication Succeeded. Initializing WebRTC session.');
          setPairingState('success');
          setSessionActive(true);
          setMode('session');
          handleAutoTrustDevice();
        }

        // Process any queued signals in Vercel mode
        if (msg.signals && msg.signals.length > 0) {
          for (const sig of msg.signals) {
            handleSignalMessage(sig);
          }
        }
        break;
      }

      case 'connection-declined':
      case 'declined':
        setPairingState('failed');
        setPairingMessage('The remote device declined the connection request.');
        addSecurityLog('NET', 'Connection declined or aborted by peer.');
        cleanupConnections();
        break;

      case 'error':
        setPairingState('failed');
        setPairingMessage(msg.message);
        addSecurityLog('NET', `Server reported error: ${msg.message}`);
        break;

      case 'peer-disconnected':
        addSecurityLog('NET', `Remote peer disconnected: ${msg.message}`);
        setMode('select');
        setSessionActive(false);
        cleanupConnections();
        break;

      case 'signal':
        handleSignalMessage(msg.signal);
        break;
    }
  };

  const handleSignalMessage = (signal) => {
    if (signal && signal.type === 'chat') {
      setChatMessages(prev => [...prev, { sender: 'peer', text: signal.text, time: new Date().toLocaleTimeString() }]);
    } else if (signal && signal.type === 'clipboard') {
      addSecurityLog('SESSION', `Clipboard synchronized from peer.`);
      setClipboardSynced(true);
      setTimeout(() => setClipboardSynced(false), 2000);
    }
  };

  // Automatically trust device
  const handleAutoTrustDevice = async () => {
    if (!peerCert) return;
    const isAlreadyTrusted = trustedDevices.some(d => d.id === peerCert.id);
    if (!isAlreadyTrusted) {
      await window.electronAPI.addTrustedDevice({
        id: peerCert.id,
        label: `${peerCert.owner}'s Key`,
        owner: peerCert.owner,
        publicKey: peerCert.publicKey
      });
      loadTrustedDevices();
    }
  };

  // Sender starts connection
  const handleConnect = async () => {
    if (!connectCodeInput.trim()) return;
    setPairingState('requesting');
    setPairingMessage(`Connecting to Receiver code ${connectCodeInput}...`);

    if (isHttpServer()) {
      try {
        const res = await fetch(`${serverUrl}/api/connect-request`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            senderId: clientId,
            code: connectCodeInput,
            cert: activeUSB.cert,
            computerName
          })
        });
        const data = await res.json();
        if (data.success) {
          handleIncomingMessage({
            type: 'auth-challenge',
            challenge: data.challenge,
            peerCert: data.peerCert,
            peerComputerName: data.peerComputerName
          });
        } else {
          throw new Error(data.error);
        }
      } catch (err) {
        setPairingState('failed');
        setPairingMessage(`Connection error: ${err.message}`);
      }
    } else {
      if (!socketRef.current) return;
      socketRef.current.send(JSON.stringify({
        type: 'connect-request',
        code: connectCodeInput
      }));
    }
  };

  // Receiver actions
  const handleAcceptRequest = async () => {
    if (!incomingRequest) return;
    
    setPairingState('authenticating');
    setPairingMessage('Signing security challenge...');
    
    const signature = await window.electronAPI.signChallenge(incomingRequest.challenge, activeUSB.privateKey);
    
    if (isHttpServer()) {
      await fetch(`${serverUrl}/api/incoming-request-response`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ receiverId: clientId, accept: true })
      });
      await fetch(`${serverUrl}/api/submit-signature`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: clientId, role: 'receiver', signature })
      });
    } else {
      if (!socketRef.current) return;
      socketRef.current.send(JSON.stringify({
        type: 'incoming-request-response',
        accept: true
      }));
      socketRef.current.send(JSON.stringify({
        type: 'auth-signature',
        signature: signature
      }));
    }

    setIncomingRequest(null);
  };

  const handleDeclineRequest = async () => {
    if (!incomingRequest) return;

    if (isHttpServer()) {
      await fetch(`${serverUrl}/api/incoming-request-response`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ receiverId: clientId, accept: false })
      });
    } else {
      if (!socketRef.current) return;
      socketRef.current.send(JSON.stringify({
        type: 'incoming-request-response',
        accept: false
      }));
    }

    setIncomingRequest(null);
    setPairingState('idle');
  };

  // Send a signal or chat
  const sendSignal = async (signalData) => {
    if (isHttpServer()) {
      try {
        await fetch(`${serverUrl}/api/send-signal`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ id: clientId, role: mode, signal: signalData })
        });
      } catch (err) {
        console.error('Failed to send HTTP signal:', err);
      }
    } else {
      if (!socketRef.current) return;
      socketRef.current.send(JSON.stringify({
        type: 'signal',
        signal: signalData
      }));
    }
  };

  // Send a chat message
  const handleSendChat = () => {
    if (!chatInput.trim()) return;
    
    sendSignal({
      type: 'chat',
      text: chatInput
    });

    setChatMessages(prev => [...prev, { sender: 'me', text: chatInput, time: new Date().toLocaleTimeString() }]);
    setChatInput('');
  };

  // Clipboard sync
  const handleSyncClipboard = () => {
    sendSignal({
      type: 'clipboard'
    });
    setClipboardSynced(true);
    setTimeout(() => setClipboardSynced(false), 2000);
  };

  // Terminate active session
  const handleEndSession = async () => {
    if (isHttpServer()) {
      await fetch(`${serverUrl}/api/disconnect`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ id: clientId, role: mode })
      });
    } else {
      if (socketRef.current) {
        socketRef.current.send(JSON.stringify({
          type: 'disconnect-peer'
        }));
      }
    }
    setMode('select');
    setSessionActive(false);
    cleanupConnections();
  };

  // Remove trusted device
  const handleRemoveTrusted = async (id) => {
    await window.electronAPI.removeTrustedDevice(id);
    loadTrustedDevices();
    addSecurityLog('DB', `Removed trusted key ID: ${id}`);
  };

  return (
    <div className="app-container">
      {/* Electron custom title bar */}
      <div className="titlebar-spacer">
        <span>USB REMOTE CONNECT SECURE SHELL</span>
      </div>

      <div className="layout-content">
        {/* Sidebar */}
        <aside className="sidebar">
          {/* Logo / Title */}
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '2rem' }}>
            <div style={{ background: 'var(--gradient-neon)', padding: '0.5rem', borderRadius: '8px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
              <Shield className="animate-spin-slow" size={24} color="white" />
            </div>
            <div>
              <h2 style={{ fontSize: '1.1rem', fontWeight: 700 }}>USB REMOTE</h2>
              <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', letterSpacing: '0.1em' }}>MILITARY-GRADE P2P</p>
            </div>
          </div>

          {/* Active PC status */}
          <div style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid var(--glass-border)', padding: '0.75rem', borderRadius: '10px', marginBottom: '1.5rem', fontSize: '0.85rem' }}>
            <span style={{ color: 'var(--text-muted)' }}>Local Host:</span>
            <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '0.25rem', fontWeight: 'bold' }}>
              <Laptop size={16} className="accent-text" />
              <span>{computerName}</span>
            </div>
          </div>

          {/* USB Security Key Section */}
          <div style={{ marginBottom: '1.5rem' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.75rem' }}>
              <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 600 }}>SECURITY KEYS</span>
              <button onClick={refreshDrives} className="btn" style={{ padding: '0.25rem', background: 'transparent', color: 'var(--text-muted)' }}>
                <RefreshCw size={14} />
              </button>
            </div>

            {activeUSB ? (
              <div className="usb-card active">
                <div className="usb-icon-wrapper">
                  <Usb size={20} />
                </div>
                <div style={{ overflow: 'hidden', flex: 1 }}>
                  <p style={{ fontSize: '0.85rem', fontWeight: 'bold', color: 'white' }}>{activeUSB.label}</p>
                  <p style={{ fontSize: '0.7rem', color: 'var(--success)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                    <ShieldCheck size={12} /> ID: {activeUSB.cert.id.substring(0, 8)}...
                  </p>
                </div>
              </div>
            ) : (
              <div className="usb-card">
                <div className="usb-icon-wrapper">
                  <Usb size={20} />
                </div>
                <div>
                  <p style={{ fontSize: '0.85rem', fontWeight: 'bold', color: 'var(--text-muted)' }}>No Security Key</p>
                  <p style={{ fontSize: '0.7rem', color: 'var(--danger)', display: 'flex', alignItems: 'center', gap: '0.25rem' }}>
                    <AlertCircle size={12} /> Insert registered USB drive
                  </p>
                </div>
              </div>
            )}
          </div>

          {/* Navigation/Actions in Sidebar */}
          <div style={{ flex: 1 }}>
            {mode !== 'session' && (
              <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                <button 
                  onClick={() => { setMode('select'); cleanupConnections(); }}
                  className={`btn ${mode === 'select' ? 'btn-primary' : 'btn-secondary'}`}
                  style={{ justifyContent: 'flex-start' }}
                >
                  <Radio size={16} /> Mode Selection
                </button>
                <button 
                  onClick={() => setShowConfig(!showConfig)}
                  className={`btn ${showConfig ? 'btn-primary' : 'btn-secondary'}`}
                  style={{ justifyContent: 'flex-start' }}
                >
                  <Settings size={16} /> Connection Panel
                </button>
              </div>
            )}
          </div>

          {/* Server Connection status */}
          <div style={{ fontSize: '0.75rem', borderTop: '1px solid var(--glass-border)', paddingTop: '1rem', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
            <span style={{ color: 'var(--text-muted)' }}>Signaling Relay:</span>
            <span style={{ 
              color: serverStatus === 'connected' ? 'var(--success)' : serverStatus === 'connecting' ? 'var(--warning)' : 'var(--danger)',
              display: 'flex', alignItems: 'center', gap: '0.25rem', fontWeight: 'bold'
            }}>
              <span style={{ 
                width: '6px', height: '6px', borderRadius: '50%', 
                background: serverStatus === 'connected' ? 'var(--success)' : serverStatus === 'connecting' ? 'var(--warning)' : 'var(--danger)',
                display: 'inline-block'
              }}></span>
              {serverStatus.toUpperCase()}
            </span>
          </div>
        </aside>

        {/* Main Content Area */}
        <main className="main-view">
          
          {/* Config Panel Overlay */}
          {showConfig && (
            <div className="glass-panel" style={{ marginBottom: '1.5rem', animation: 'fadeIn 0.3s' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
                <h3 className="accent-text" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}><Settings size={18} /> Network & Key Administration Panel</h3>
                <button onClick={() => setShowConfig(false)} className="btn btn-secondary" style={{ padding: '0.25rem' }}><X size={16} /></button>
              </div>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
                {/* Cloud and Dev Server config */}
                <div>
                  <h4 style={{ fontSize: '0.9rem', marginBottom: '0.5rem', color: 'white', display: 'flex', alignItems: 'center', gap: '0.25rem' }}><Cloud size={16} /> Signaling Server Configuration</h4>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
                    Toggle between your local WebSocket server (dev) and your deployed Vercel cloud serverless signaling URL.
                  </p>

                  <div className="form-group">
                    <label className="form-label">SERVER URL (WS or HTTPS)</label>
                    <input 
                      value={serverUrl}
                      onChange={(e) => setServerUrl(e.target.value)}
                      placeholder="ws://localhost:9000  OR  https://myapp.vercel.app"
                      className="form-input"
                      style={{ fontSize: '0.85rem' }}
                    />
                  </div>

                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '0.75rem', borderRadius: '8px', border: '1px solid var(--glass-border)', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.25rem', color: 'white', marginBottom: '0.25rem', fontWeight: 'bold' }}>
                      <Link2 size={12} /> Auto Protocol Detection
                    </div>
                    If URL begins with <code>http</code>/<code>https</code>, client switches to Serverless Polling. 
                    If it begins with <code>ws</code>/<code>wss</code>, it uses persistent sockets.
                  </div>
                </div>

                {/* Key Registration */}
                <div>
                  <h4 style={{ fontSize: '0.9rem', marginBottom: '0.5rem', color: 'white', display: 'flex', alignItems: 'center', gap: '0.25rem' }}><Key size={16} /> Format Removable Security Key</h4>
                  <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '1rem' }}>
                    Choose a connected removable USB drive letter to sign it with a custom alias name.
                  </p>

                  <div className="form-group">
                    <label className="form-label">Key Alias Name</label>
                    <input 
                      value={registerLabel}
                      onChange={(e) => setRegisterLabel(e.target.value)}
                      placeholder="e.g. Rajnish PC Key"
                      className="form-input"
                      style={{ padding: '0.5rem' }}
                    />
                  </div>

                  <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                    {drives.length === 0 ? (
                      <div style={{ display: 'flex', flexDirection: 'column', gap: '0.5rem' }}>
                        <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>No removable USB drives detected. Plug in your pendrive.</span>
                        {/* developer helpers */}
                        <div style={{ display: 'flex', gap: '0.25rem' }}>
                          <button onClick={() => handleSimulateUSB(simFolderA, 'Simulated Key A')} className="btn btn-secondary" style={{ padding: '0.25rem 0.5rem', fontSize: '0.7rem' }}>Mount Sim USB A</button>
                          <button onClick={() => handleSimulateUSB(simFolderB, 'Simulated Key B')} className="btn btn-secondary" style={{ padding: '0.25rem 0.5rem', fontSize: '0.7rem' }}>Mount Sim USB B</button>
                        </div>
                      </div>
                    ) : (
                      drives.map(d => (
                        <div key={d.driveLetter} style={{ display: 'flex', gap: '0.25rem' }}>
                          <button 
                            onClick={() => handleFormatDrive(d.driveLetter)}
                            className="btn btn-primary"
                            style={{ flex: 1, padding: '0.5rem', fontSize: '0.8rem' }}
                          >
                            Format & Sign Drive {d.driveLetter} ({d.label})
                          </button>
                          {d.isSimulated && (
                            <button onClick={() => handleRemoveSimulatedUSB(d.driveLetter)} className="btn btn-danger" style={{ padding: '0.5rem' }}>
                              Eject
                            </button>
                          )}
                        </div>
                      ))
                    )}
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* 1. STARTUP: Insert key / Guide */}
          {!activeUSB && (
            <div className="glass-panel" style={{ margin: 'auto', maxWidth: '580px', textAlign: 'center' }}>
              <div style={{ width: '80px', height: '80px', background: 'rgba(99, 102, 241, 0.1)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.5rem' }}>
                <Key size={40} className="accent-text" />
              </div>
              <h2 style={{ fontSize: '1.75rem', marginBottom: '0.75rem' }}>USB Security Key Authentication</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem', fontSize: '0.95rem', lineHeight: '1.5' }}>
                Please insert a registered USB Security Key (pendrive) into your computer's USB port. 
                The system will automatically authenticate using public/private key signing.
              </p>

              <div style={{ background: 'rgba(7, 10, 19, 0.5)', border: '1px solid var(--glass-border)', padding: '1rem', borderRadius: '10px', textAlign: 'left', marginBottom: '1.5rem' }}>
                <p style={{ fontSize: '0.85rem', fontWeight: 'bold', color: 'white', marginBottom: '0.25rem' }}>Quick Dev/Simulation Override</p>
                <p style={{ fontSize: '0.75rem', color: 'var(--text-secondary)', marginBottom: '0.75rem' }}>
                  If testing locally, click below to mount a virtual drive in the project folder and configure a key via Settings:
                </p>
                <div style={{ display: 'flex', gap: '0.5rem' }}>
                  <button onClick={() => { handleSimulateUSB('./usb_key_a', 'Alpha Key'); setShowConfig(true); }} className="btn btn-secondary" style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                    Mount Sim USB A
                  </button>
                  <button onClick={() => { handleSimulateUSB('./usb_key_b', 'Beta Key'); setShowConfig(true); }} className="btn btn-secondary" style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                    Mount Sim USB B
                  </button>
                </div>
              </div>

              <div style={{ display: 'flex', justifyContent: 'center', gap: '0.5rem', fontSize: '0.8rem', color: 'var(--text-muted)' }}>
                <Lock size={14} />
                <span>AES-256-GCM Session Encryption Active</span>
              </div>
            </div>
          )}

          {/* 2. SELECT MODE */}
          {activeUSB && mode === 'select' && (
            <div className="glass-panel" style={{ margin: 'auto', maxWidth: '500px', textAlign: 'center' }}>
              <h2 style={{ fontSize: '1.5rem', marginBottom: '0.5rem' }}>Select Mode</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem', fontSize: '0.85rem' }}>
                Choose whether you want to share your desktop (Receiver) or control another computer (Sender).
              </p>

              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem', marginBottom: '1.5rem' }}>
                <button onClick={() => initializeConnection('sender')} className="btn btn-secondary" style={{ flexDirection: 'column', padding: '2rem 1.5rem', gap: '1rem', borderRadius: '12px' }}>
                  <Radio size={32} className="accent-text" />
                  <div>
                    <h4 style={{ fontWeight: 'bold', fontSize: '1.1rem', color: 'white' }}>Sender</h4>
                    <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>Control a remote computer</p>
                  </div>
                </button>

                <button onClick={() => initializeConnection('receiver')} className="btn btn-secondary" style={{ flexDirection: 'column', padding: '2rem 1.5rem', gap: '1rem', borderRadius: '12px' }}>
                  <Laptop size={32} className="accent-text" />
                  <div>
                    <h4 style={{ fontWeight: 'bold', fontSize: '1.1rem', color: 'white' }}>Receiver</h4>
                    <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)', marginTop: '0.25rem' }}>Share your local screen</p>
                  </div>
                </button>
              </div>

              <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Current Key: {activeUSB.label} ({activeUSB.cert.id.substring(0, 8)}...)</span>
            </div>
          )}

          {/* 3. SENDER VIEW */}
          {activeUSB && mode === 'sender' && !sessionActive && (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 340px', gap: '1.5rem', flex: 1 }}>
              {/* Connect interface */}
              <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', justifyContent: 'center', alignItems: 'center' }}>
                <div style={{ maxWidth: '380px', width: '100%', textAlign: 'center' }}>
                  <div style={{ width: '64px', height: '64px', background: 'rgba(99, 102, 241, 0.1)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1rem' }}>
                    <Laptop size={32} className="accent-text" />
                  </div>
                  
                  <h2 style={{ fontSize: '1.5rem', marginBottom: '1.5rem' }}>Secure Connection Setup</h2>
                  
                  {pairingState === 'idle' || pairingState === 'failed' ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                      <div className="form-group">
                        <label className="form-label">ENTER RECEIVER SECURE CODE</label>
                        <input 
                          value={connectCodeInput}
                          onChange={(e) => setConnectCodeInput(e.target.value)}
                          placeholder="e.g. 123456" 
                          className="form-input"
                          style={{ textAlign: 'center', fontSize: '1.25rem', letterSpacing: '0.2em', fontWeight: 'bold' }}
                          maxLength={6}
                        />
                      </div>

                      <button 
                        onClick={handleConnect}
                        disabled={!connectCodeInput || connectCodeInput.length < 6}
                        className="btn btn-primary"
                        style={{ width: '100%', padding: '0.9rem' }}
                      >
                        Initiate Secure Session
                      </button>

                      {pairingState === 'failed' && (
                        <p style={{ color: 'var(--danger)', fontSize: '0.8rem', marginTop: '0.5rem', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '0.25rem' }}>
                          <AlertCircle size={14} /> {pairingMessage}
                        </p>
                      )}
                    </div>
                  ) : (
                    <div style={{ padding: '2rem 0' }}>
                      <RefreshCw className="animate-spin-slow accent-text" size={36} style={{ margin: '0 auto 1.5rem' }} />
                      <h4 style={{ color: 'white', marginBottom: '0.5rem' }}>{pairingState.toUpperCase()}</h4>
                      <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{pairingMessage}</p>
                    </div>
                  )}
                </div>
              </div>

              {/* Saved/Trusted Devices Sidebar */}
              <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column' }}>
                <h3 style={{ fontSize: '0.95rem', marginBottom: '1rem', color: 'white', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <ShieldCheck size={16} /> Trusted Devices
                </h3>
                
                <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                  {trustedDevices.length === 0 ? (
                    <div style={{ color: 'var(--text-muted)', fontSize: '0.8rem', textAlign: 'center', padding: '2rem 0' }}>
                      No trusted devices saved yet. Connections require manual approval first.
                    </div>
                  ) : (
                    trustedDevices.map(device => (
                      <div key={device.id} style={{ background: 'rgba(255,255,255,0.02)', border: '1px solid var(--glass-border)', padding: '0.75rem', borderRadius: '10px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                        <div>
                          <p style={{ fontSize: '0.85rem', fontWeight: 'bold', color: 'white' }}>{device.label}</p>
                          <p style={{ fontSize: '0.7rem', color: 'var(--text-muted)' }}>Computer: {device.owner}</p>
                        </div>
                        <div style={{ display: 'flex', gap: '0.25rem' }}>
                          <button 
                            onClick={() => { setConnectCodeInput(''); alert(`To connect to ${device.owner}, please enter their current 6-digit receiver code.`); }} 
                            className="btn btn-secondary" 
                            style={{ padding: '0.25rem 0.5rem', fontSize: '0.7rem' }}
                          >
                            Use
                          </button>
                          <button onClick={() => handleRemoveTrusted(device.id)} className="btn btn-danger" style={{ padding: '0.25rem' }}>
                            <Trash2 size={12} />
                          </button>
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            </div>
          )}

          {/* 4. RECEIVER VIEW */}
          {activeUSB && mode === 'receiver' && !sessionActive && (
            <div className="glass-panel" style={{ margin: 'auto', maxWidth: '580px', width: '100%', textAlign: 'center' }}>
              <div style={{ width: '80px', height: '80px', background: 'rgba(6, 182, 212, 0.1)', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', margin: '0 auto 1.5rem' }} className="pulse-glow">
                <Radio size={36} className="accent-text" />
              </div>

              <h2 style={{ fontSize: '1.75rem', marginBottom: '0.5rem' }}>Waiting for Connection...</h2>
              <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem', fontSize: '0.9rem' }}>
                Provide the secure session code below to the sender. They will authenticate using their USB key.
              </p>

              <div style={{ background: '#070a13', border: '1px solid var(--glass-border)', borderRadius: '12px', padding: '1.5rem', display: 'inline-block', marginBottom: '2rem' }}>
                <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'block', marginBottom: '0.5rem', letterSpacing: '0.05em' }}>RECEIVER SECURE CODE</span>
                <span style={{ fontSize: '2.5rem', fontWeight: 'bold', color: 'white', letterSpacing: '0.15em' }} className="accent-text">{receiverCode}</span>
              </div>

              {/* Incoming Connection Request Modal/Popup */}
              {pairingState === 'incoming-request' && incomingRequest && (
                <div style={{ background: 'rgba(12, 16, 32, 0.95)', border: '2px solid var(--accent-indigo)', borderRadius: '16px', padding: '1.5rem', marginTop: '1rem', textAlign: 'left', animation: 'fadeIn 0.3s' }}>
                  <h3 style={{ color: 'white', marginBottom: '1rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}><AlertCircle size={20} color="var(--accent-indigo)" /> Incoming Request</h3>
                  
                  <div style={{ background: 'rgba(255,255,255,0.02)', padding: '1rem', borderRadius: '10px', marginBottom: '1.5rem', border: '1px solid var(--glass-border)' }}>
                    <p style={{ fontSize: '0.85rem', color: 'var(--text-secondary)' }}>Remote Host:</p>
                    <p style={{ fontSize: '1.1rem', fontWeight: 'bold', color: 'white', marginBottom: '0.5rem' }}>{incomingRequest.peerComputerName}</p>
                    <p style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Certificate ID: {incomingRequest.peerCert.id}</p>
                  </div>

                  <div style={{ display: 'flex', gap: '1rem' }}>
                    <button onClick={handleAcceptRequest} className="btn btn-primary" style={{ flex: 1 }}>
                      Accept & Authenticate
                    </button>
                    <button onClick={handleDeclineRequest} className="btn btn-secondary" style={{ flex: 1 }}>
                      Decline
                    </button>
                  </div>
                </div>
              )}

              {pairingState === 'authenticating' && (
                <div style={{ marginTop: '1rem' }}>
                  <RefreshCw className="animate-spin-slow accent-text" size={32} style={{ margin: '0 auto 1rem' }} />
                  <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>{pairingMessage}</p>
                </div>
              )}
            </div>
          )}

          {/* 5. ACTIVE SESSION VIEW */}
          {sessionActive && (
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 320px', gap: '1.5rem', flex: 1, overflow: 'hidden' }}>
              
              {/* Virtual Screen Panel */}
              <div className="glass-panel" style={{ display: 'flex', flexDirection: 'column', padding: '1rem', overflow: 'hidden' }}>
                {/* Header */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderBottom: '1px solid var(--glass-border)', paddingBottom: '0.75rem', marginBottom: '1rem' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <div style={{ width: '8px', height: '8px', borderRadius: '50%', background: 'var(--success)' }}></div>
                    <span style={{ fontSize: '0.9rem', fontWeight: 'bold', color: 'white' }}>SECURE LINK: {peerComputerName}</span>
                  </div>
                  
                  <div style={{ display: 'flex', alignItems: 'center', gap: '1rem', fontSize: '0.75rem', color: 'var(--text-secondary)' }}>
                    <span>Ping: <strong style={{ color: 'var(--success)' }}>{ping} ms</strong></span>
                    <span>Cipher: <strong style={{ color: 'var(--accent-cyan)' }}>AES-256-GCM</strong></span>
                    <button onClick={handleSyncClipboard} className={`btn ${clipboardSynced ? 'btn-primary' : 'btn-secondary'}`} style={{ padding: '0.25rem 0.5rem', fontSize: '0.7rem' }}>
                      <FolderSync size={12} /> {clipboardSynced ? 'Clipboard Synced!' : 'Sync Clipboard'}
                    </button>
                  </div>
                </div>

                {/* Virtual Remote Desktop Workspace (Simulated Screen) */}
                <div style={{ 
                  flex: 1, 
                  background: '#04060c', 
                  borderRadius: '12px', 
                  border: '1px solid rgba(255,255,255,0.05)', 
                  display: 'flex', 
                  flexDirection: 'column',
                  alignItems: 'center', 
                  justifyContent: 'center',
                  position: 'relative',
                  overflow: 'hidden'
                }}>
                  {/* Neon Grid background */}
                  <div style={{ 
                    position: 'absolute', 
                    top: 0, left: 0, right: 0, bottom: 0, 
                    backgroundImage: 'linear-gradient(rgba(255,255,255,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.03) 1px, transparent 1px)',
                    backgroundSize: '20px 20px'
                  }}></div>

                  <div style={{ zIndex: 1, textAlign: 'center', padding: '2rem' }}>
                    <ShieldCheck size={64} className="accent-text" style={{ marginBottom: '1rem', filter: 'drop-shadow(0 0 10px rgba(99,102,241,0.5))' }} />
                    <h3 style={{ fontSize: '1.25rem', marginBottom: '0.5rem', color: 'white' }}>Secure Session Active</h3>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', maxWidth: '380px', margin: '0 auto 1.5rem', lineHeight: '1.4' }}>
                      Peer connection successfully authenticated using USB hardware certificates. Screen and control channels are isolated.
                    </p>
                    <div style={{ display: 'flex', gap: '0.5rem', justifyContent: 'center' }}>
                      <div className="badge badge-success">MUTUAL AUTHENTICATED</div>
                      <div className="badge badge-info">DIRECT PORT RELAY</div>
                    </div>
                  </div>
                  
                  {/* Remote view details */}
                  <div style={{ position: 'absolute', bottom: '1rem', left: '1rem', fontSize: '0.7rem', color: 'var(--text-muted)', zIndex: 1 }}>
                    Secure Key ID: {peerCert?.id}
                  </div>
                </div>

                {/* Footer Controls */}
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginTop: '1rem', paddingTop: '0.75rem', borderTop: '1px solid var(--glass-border)' }}>
                  <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>Warning: Clipboard sync mirrors system clipboard changes.</span>
                  <button onClick={handleEndSession} className="btn btn-danger" style={{ padding: '0.5rem 1rem', fontSize: '0.8rem' }}>
                    <LogOut size={14} /> Close Secure Session
                  </button>
                </div>
              </div>

              {/* Chat Panel & Logs */}
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', height: '100%' }}>
                
                {/* Secure Chat */}
                <div className="glass-panel" style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: '1rem' }}>
                  <h3 style={{ fontSize: '0.9rem', marginBottom: '0.75rem', color: 'white', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <MessageSquare size={16} /> Secure Chat
                  </h3>
                  
                  {/* Messages list */}
                  <div style={{ flex: 1, overflowY: 'auto', display: 'flex', flexDirection: 'column', gap: '0.5rem', padding: '0.5rem', background: 'rgba(0,0,0,0.2)', borderRadius: '8px', marginBottom: '0.75rem' }}>
                    {chatMessages.length === 0 ? (
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', margin: 'auto', textAlign: 'center' }}>No messages exchanged.</span>
                    ) : (
                      chatMessages.map((msg, i) => (
                        <div key={i} style={{ 
                          alignSelf: msg.sender === 'me' ? 'flex-end' : 'flex-start',
                          background: msg.sender === 'me' ? 'var(--accent-indigo)' : 'var(--bg-tertiary)',
                          color: 'white',
                          padding: '0.5rem 0.75rem',
                          borderRadius: '8px',
                          maxWidth: '85%',
                          fontSize: '0.8rem',
                          position: 'relative'
                        }}>
                          <p>{msg.text}</p>
                          <span style={{ fontSize: '0.6rem', color: 'rgba(255,255,255,0.5)', display: 'block', textAlign: 'right', marginTop: '0.25rem' }}>{msg.time}</span>
                        </div>
                      ))
                    )}
                  </div>

                  {/* Message Input */}
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <input 
                      value={chatInput}
                      onChange={(e) => setChatInput(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleSendChat()}
                      placeholder="Type secure message..." 
                      className="form-input"
                      style={{ padding: '0.5rem', fontSize: '0.8rem' }}
                    />
                    <button onClick={handleSendChat} className="btn btn-primary" style={{ padding: '0.5rem' }}>
                      <Send size={14} />
                    </button>
                  </div>
                </div>

                {/* Session Security Logs */}
                <div className="glass-panel" style={{ flex: 1, display: 'flex', flexDirection: 'column', padding: '1rem' }}>
                  <h3 style={{ fontSize: '0.9rem', marginBottom: '0.75rem', color: 'white', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                    <Terminal size={16} /> Encryption Logs
                  </h3>
                  
                  <div className="logs-container" style={{ flex: 1, fontSize: '0.75rem' }}>
                    {securityLogs.filter(l => l.category === 'SECURITY' || l.category === 'NET').map((log, i) => (
                      <div key={i} className="log-line" style={{ flexDirection: 'column', gap: '0.1rem', marginBottom: '0.5rem' }}>
                        <span className="log-time" style={{ fontSize: '0.65rem' }}>{new Date(log.timestamp).toLocaleTimeString()}</span>
                        <span className="log-msg" style={{ color: log.message.includes('Succeeded') || log.message.includes('verified') ? 'var(--success)' : 'var(--text-secondary)' }}>
                          {log.message}
                        </span>
                      </div>
                    ))}
                    <div ref={logEndRef}></div>
                  </div>
                </div>

              </div>
            </div>
          )}

          {/* Bottom Security Console (Only shown outside active session) */}
          {!sessionActive && (
            <div className="glass-panel" style={{ marginTop: '1.5rem', display: 'flex', flexDirection: 'column', padding: '1rem' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '0.5rem' }}>
                <h3 style={{ fontSize: '0.85rem', color: 'white', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  <Activity size={16} /> Local Security Audit Log
                </h3>
                <button onClick={() => { window.electronAPI.clearLogs(); setSecurityLogs([]); }} className="btn" style={{ padding: '0.25rem', background: 'transparent', color: 'var(--text-muted)', fontSize: '0.75rem' }}>
                  Clear Audit Logs
                </button>
              </div>

              <div className="logs-container">
                {securityLogs.length === 0 ? (
                  <span style={{ color: 'var(--text-muted)', margin: 'auto' }}>Logs empty. No operations logged.</span>
                ) : (
                  securityLogs.map((log, i) => (
                    <div key={i} className="log-line">
                      <span className="log-time">{new Date(log.timestamp).toLocaleTimeString()}</span>
                      <span className="log-cat" style={{ color: log.category === 'SECURITY' ? 'var(--accent-violet)' : log.category === 'USB' ? 'var(--accent-cyan)' : 'var(--success)' }}>
                        [{log.category}]
                      </span>
                      <span className="log-msg">{log.message}</span>
                    </div>
                  ))
                )}
                <div ref={logEndRef}></div>
              </div>
            </div>
          )}

        </main>
      </div>
    </div>
  );
}
